#-------------------------------
# 啟動相關
Start:
  Token: "" # 啟動令牌
  Client_ID: "" # 機器人 ID

#-------------------------------
# 記錄器相關
Logger:
  Settings:
    Channel: "" #日誌頻道 ID
    Time_Zone: 0 # 時區偏移

  Type:
    Member: true # 成員加入與離開
    Message:
      Create: false # 成員傳送訊息
      Update: true # 訊息被變更
      Delete: true # 訊息被刪除

    Role: true # 身分組被變更
    Voice: true # 語音活動    

#-------------------------------
# 嵌入介面
Embed_Color: 0xf8b840 # 側邊欄顏色
Embed_Color_error: 0x2F3136 # 側邊欄顏色

#-------------------------------
# 自定義訊息
Message:
  Ready_Type: 5 # 0 正在玩、1 正在直播、2 正在聽、3 正在看、5競爭

  Member:
    Join: # 隨機歡迎訊息
      - "歡迎來到伺服器！"
      - "社群有你更精彩！"
      - "歡迎加入我們的大家庭！"

    Leave: # 隨機離開訊息
      - "感謝你的陪伴，希望未來還能再見～"
      - "雖然你離開了，但你的足跡永遠留在我們的心中～"
      - "雖然心中不捨，但希望你一切順利～"

  Stream: # 隨機直播訊息
    - "現在正直播精彩內容，來一起加入吧！"
    - "直播現在開始！別錯過，一起觀看吧！"
    - "開播啦！一起享受這場直播！"

#-------------------------------
# 表情符號
Emoji:
  Commands:
    About: "🔰"
    Announcement: "📢"
    Message_Delete: "🗑️"
    Ping: "🏓"
    Deepseek: "🐋"
    Hitokoto: "🍵"
    IP_Query: "ℹ️"
    Minecraft: "🧱"
    
  Event:
    Member: "🚧"

  Error_Reply: "❌"
  Loading: "..."

#-------------------------------
# 指令設定
Commands:
  Message_Delete:
    Limit: 30 #最多支援一次刪除 100 則訊息

  Minecraft:
    Hypixel: "mc.hypixel.net" #伺服器名稱與 IP，可繼續向下延伸，最多支援 25 個

#-------------------------------
# 直播相關
Stream:
  User_Login: "" # 要監控的頻道名稱
  User_Avatar: "" # 要監控的使用者頭像網址
  Role: "" # 要提及的身分組 ID ，若不填寫則預設為 @everyone

#-------------------------------
# 關於
About:
  Bot_Nicdname: "みやこ" # 機器人暱稱
  Introduce: "みやこ機器人第三代！\n這是一個基於 discord.js 集合許多功能的綜合型機器人，\n本專案目前仍在積極開發中！" # 關於機器人的介紹
  Provider: "" # 服務提供者，請填入您的 Discord 數字 ID
  Repository: "https://github.com/miguotw/MiYako-DCB" # 專案連結 

#-------------------------------
# 外部 API
API:
  Twitch:
    Client_ID: "" # 暫時無作用
    Access_Token: "" # 暫時無作用