#-------------------------------
# å•Ÿå‹•ç›¸é—œ
Start:
  Token: "" # å•Ÿå‹•ä»¤ç‰Œ
  Client_ID: "" # æ©Ÿå™¨äºº ID

#-------------------------------
# è¨˜éŒ„å™¨ç›¸é—œ
Logger:
  Settings:
    Channel: "" #æ—¥èªŒé »é“ ID
    Time_Zone: 0 # æ™‚å€åç§»

  Type:
    Member: true # æˆå“¡åŠ å…¥èˆ‡é›¢é–‹
    Message:
      Create: false # æˆå“¡å‚³é€è¨Šæ¯
      Update: true # è¨Šæ¯è¢«è®Šæ›´
      Delete: true # è¨Šæ¯è¢«åˆªé™¤

    Role: true # èº«åˆ†çµ„è¢«è®Šæ›´
    Voice: true # èªéŸ³æ´»å‹•    

#-------------------------------
# åµŒå…¥ä»‹é¢
Embed_Color: 0xf8b840 # å´é‚Šæ¬„é¡è‰²
Embed_Color_error: 0x2F3136 # å´é‚Šæ¬„é¡è‰²

#-------------------------------
# è‡ªå®šç¾©è¨Šæ¯
Message:
  Ready_Type: 5 # 0 æ­£åœ¨ç©ã€1 æ­£åœ¨ç›´æ’­ã€2 æ­£åœ¨è½ã€3 æ­£åœ¨çœ‹ã€5ç«¶çˆ­

  Member:
    Join: # éš¨æ©Ÿæ­¡è¿è¨Šæ¯
      - "æ­¡è¿ä¾†åˆ°ä¼ºæœå™¨ï¼"
      - "ç¤¾ç¾¤æœ‰ä½ æ›´ç²¾å½©ï¼"
      - "æ­¡è¿åŠ å…¥æˆ‘å€‘çš„å¤§å®¶åº­ï¼"

    Leave: # éš¨æ©Ÿé›¢é–‹è¨Šæ¯
      - "æ„Ÿè¬ä½ çš„é™ªä¼´ï¼Œå¸Œæœ›æœªä¾†é‚„èƒ½å†è¦‹ï½"
      - "é›–ç„¶ä½ é›¢é–‹äº†ï¼Œä½†ä½ çš„è¶³è·¡æ°¸é ç•™åœ¨æˆ‘å€‘çš„å¿ƒä¸­ï½"
      - "é›–ç„¶å¿ƒä¸­ä¸æ¨ï¼Œä½†å¸Œæœ›ä½ ä¸€åˆ‡é †åˆ©ï½"

  Stream: # éš¨æ©Ÿç›´æ’­è¨Šæ¯
    - "ç¾åœ¨æ­£ç›´æ’­ç²¾å½©å…§å®¹ï¼Œä¾†ä¸€èµ·åŠ å…¥å§ï¼"
    - "ç›´æ’­ç¾åœ¨é–‹å§‹ï¼åˆ¥éŒ¯éï¼Œä¸€èµ·è§€çœ‹å§ï¼"
    - "é–‹æ’­å•¦ï¼ä¸€èµ·äº«å—é€™å ´ç›´æ’­ï¼"

#-------------------------------
# è¡¨æƒ…ç¬¦è™Ÿ
Emoji:
  Commands:
    Announcement: "ğŸ“¢"
    Message_Delete: "ğŸ—‘ï¸"
    Stream: "ğŸ˜"
    Ping: "ğŸ“"
    Deepseek: "ğŸ‹" 
    Hitokoto: "ğŸµ"
    Minecraft: "ğŸ§±"
    
  Event:
    Member: "ğŸš§"

  Error_Reply: "âŒ"
  Loading: "..."

#-------------------------------
# ç®¡ç†åŠŸèƒ½
Admin:
  Message_Delete:
    Limit: 30 #æœ€å¤šæ”¯æ´ä¸€æ¬¡åˆªé™¤ 100 å‰‡è¨Šæ¯

#-------------------------------
# ç›´æ’­ç›¸é—œ
Stream:
  User_Login: "" # è¦ç›£æ§çš„é »é“åç¨±
  User_Avatar: "" # è¦ç›£æ§çš„ä½¿ç”¨è€…é ­åƒç¶²å€
  Role: "" # è¦æåŠçš„èº«åˆ†çµ„ ID ï¼Œè‹¥ä¸å¡«å¯«å‰‡é è¨­ç‚º @everyone

#-------------------------------
# å¤–éƒ¨ API
API:
  Hitokoto:  https://v1.hitokoto.cn/?c=a&encode=json

  Twitch:
    Client_ID: "" # æš«æ™‚ç„¡ä½œç”¨
    Access_Token: "" # æš«æ™‚ç„¡ä½œç”¨

  Minecraft:
    Starlight_Skin: "https://starlightskins.lunareclipse.studio"
    Minotar: "https://minotar.net"
    Mcsrvstat: "https://api.mcsrvstat.us"
